cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/versions'
tap 'puma/puma'

# Install prerequisite dependencies
brew 'coreutils'
brew 'moreutils'
brew 'findutils'
brew 'openssl'
brew 'readline'
brew 'gpg'

brew 'ack'
brew 'fd'
brew 'jp2a'
brew 'jq'
brew 'libgit2'
brew 'imagemagick'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'redis'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'mackup'
brew 'youtube-dl'
brew 'watchman'
brew 'zplug'
brew 'fzf'
brew 'git'
brew 'git-extras'
brew 'python'
brew 'tree'
brew 'wifi-password'
brew 'TomAnthony/brews/itermocil'
brew 'source-highlight'
brew 'brew-cask-completion'
brew 'thefuck'

# Install Apps
cask '1password'
cask 'dropbox'
cask 'alfred'
cask 'appcleaner'
cask 'dash'
cask 'iterm2'
cask 'macdown'
cask 'firefox'
cask 'fluid'
cask 'plex-media-server'
cask 'google-chrome'
cask 'kap'
cask 'moom'
cask 'transmission'
cask 'rocket'
cask 'paw'
cask 'rdm'
cask 'rowanj-gitx'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'sourcetree'
cask 'github-desktop'
cask 'visual-studio-code'
cask 'the-unarchiver'
cask 'nordvpn'
cask 'utc-menu-clock'
cask 'vlc'
cask 'whatsapp'
cask 'abstract'
cask 'muzzle'

# App Store
mas 'Amphetamine', id: 937984704
mas 'Postico', id: 1031280567
mas 'BetterSnapTool', id: 417375580
