#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

confirm() {
  echo -n "$1 (y/n)? "
  read answer

  if echo "$answer" | grep -iq "^n" ;then
    return 1; # No
  else
    return 0; # Yes
  fi
}

if confirm "Install homebrew dependencies" ;then
  echo "› Running: bundle install"
  brew bundle
  echo "› Done."
else
  echo "› Skipped."
fi

if confirm "Is Dropbox set up" ;then
  echo "› Sweet!"
else
  echo "› Please setup Dropbox before continuing."
  echo "› Exiting."
  exit
fi

# find the installers and run them iteratively
echo "› Running install scripts..."
find . -name install.sh |
while read installer ;
do
  echo "›   Installing ${installer}..."
  sh -c "${installer}" ;
done
